### ISSUE TITLE
Bif open error

### ISSUE THREAD

**Issue by dreamworker100** [openslide/openslide-winbuild#30] opened 2022-06-16 06:18 UTC
I try to open bif file. but  openslide.lowlevel.OpenSlideError: Bad direction attribute "LEFT"

I googled below answer 2018. but window binary version is 2017. 
I use windows.  and how can I fix this problem. 

Support for Tile Joint Left Direction #246
I have access to some .bif files which have the TileJointInfo direction attribute set to LEFT rather than RIGHT. Openslide doesn’t currently support such files so I have made some simple changes so they can be opened. I have done some testing opening .bif files containing the LEFT join direction and the resulting image is almost exactly the same when processed as if it had the direction attribute set to RIGHT. Please could you consider merging this change into openslide to support files with this attribute!

**Comment by bgilbert** [comment] 2022-06-16 22:10
Closing as duplicate of openslide/openslide#234.

**Closed by bgilbert** 2022-06-16 22:10 UTC
